name: salmaproject_new1
description: "A new Flutter project."
ppublish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flutter_svg: ^2.0.9
  get_it: ^8.0.3
  carousel_slider: ^5.1.1
  image_picker: ^1.0.4  # أو أي نسخة متوافقة

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  convert: ^3.1.2
  flutter_bloc: ^9.1.1
  http: ^1.1.0
  dartz: ^0.10.1

flutter:


  uses-material-design: true


  assets:
    - assets/anmation/
    - assets/svg/
    - assets/images/
    - assets/images/default_avatar.png

