// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3BPikGh_ESlEqMsgrYv3TUzLiTwwiqk',
    appId: '1:242975689044:web:38b3cf8cec732b631c60c1',
    messagingSenderId: '242975689044',
    projectId: 'afnan-4df33',
    authDomain: 'afnan-4df33.firebaseapp.com',
    storageBucket: 'afnan-4df33.firebasestorage.app',
    measurementId: 'G-9FF80RMBXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlyZEHh00lTUoYzazzgmrI0FgNlffGB4',
    appId: '1:242975689044:android:ec7309fd422184121c60c1',
    messagingSenderId: '242975689044',
    projectId: 'afnan-4df33',
    storageBucket: 'afnan-4df33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5HEg5PcEHuUVbqpG_v03g-EGMDQdBDZE',
    appId: '1:242975689044:ios:e4e0a6664a9a867c1c60c1',
    messagingSenderId: '242975689044',
    projectId: 'afnan-4df33',
    storageBucket: 'afnan-4df33.firebasestorage.app',
    iosBundleId: 'com.example.salmaprojectNew1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5HEg5PcEHuUVbqpG_v03g-EGMDQdBDZE',
    appId: '1:242975689044:ios:e4e0a6664a9a867c1c60c1',
    messagingSenderId: '242975689044',
    projectId: 'afnan-4df33',
    storageBucket: 'afnan-4df33.firebasestorage.app',
    iosBundleId: 'com.example.salmaprojectNew1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw3BPikGh_ESlEqMsgrYv3TUzLiTwwiqk',
    appId: '1:242975689044:web:cfa85142be8cfcda1c60c1',
    messagingSenderId: '242975689044',
    projectId: 'afnan-4df33',
    authDomain: 'afnan-4df33.firebaseapp.com',
    storageBucket: 'afnan-4df33.firebasestorage.app',
    measurementId: 'G-9S5K1EMZF4',
  );
}
